///////////////////////////////////////////////////////////////////////////////
// ApartInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ApartServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
