///////////////////////////////////////////////////////////////////////////////
// ApartClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ApartClassFactory.h"
#include "ApartServices.h"
#include "ApartVersion.h"
#include "Auto.h"

BEGIN_CLASS_MAP(CApartClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_ApartCAuto, SRVNAME_APART "!CAuto", CAuto)
///</AutoGeneratedContent>
END_CLASS_MAP()

CApartClassFactory::CApartClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_APART));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Apart));
#endif //defined(TCDBG_UNIT_VERSION)
}

