///////////////////////////////////////////////////////////////////////////////
// ApartServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Apart = 0x3F000000;
#define SRVNAME_APART "Apart"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ApartCAuto = {0x7c1c3e9f,0x9ee9,0x4de9,{0x93,0x8a,0x67,0x56,0x58,0xe2,0xda,0x40}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_AutoParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _AutoParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} AutoParameter, *PAutoParameter;

typedef struct _AutoInputs
{
	USHORT EncRawIN;
} AutoInputs, *PAutoInputs;

typedef struct _AutoOutputs
{
	SHORT VolCnt;
} AutoOutputs, *PAutoOutputs;

#pragma pack(push,1)
typedef struct _AutoEncoder
{
	USHORT EncRaw_current;
	USHORT EncRaw_pre;
	LONGLONG Enc_diff;
	double Angle;
	double Angle_current;
	double Angle_pre;
	double AngVel;
} AutoEncoder, *PAutoEncoder;
#pragma pack(pop)

typedef struct _AutoControl
{
	double Voltage;
	double Angle_Err;
	double AngVel_Err;
	double Angle_ErrInt;
	double Angle_Des;
	double AngVel_Des;
} AutoControl, *PAutoControl;

typedef struct _AutoTrajecory
{
	double a[6];
	double TrajErr;
} AutoTrajecory, *PAutoTrajecory;

#pragma pack(push,1)
typedef struct _AutoSafe
{
	bool SW;
} AutoSafe, *PAutoSafe;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_AutoInputs 0
#define ADI_AutoOutputs 1
#define ADI_AutoEncoder 4
#define ADI_AutoControl 5
#define ADI_AutoTrajecory 6
#define ADI_AutoSafe 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
